### PR TITLE
False positive checks

### LINKED ISSUE #21: False positives
I am seeing a number of words and phrases that are wrongly identified as profane. For example:
shoe
as sure
I have a hole in my pocket
album
coke
scrape

Do you have any ideas how to address these? I'll send you something if I can come up with a solution.

### PR DESCRIPTION
**Pull request by developerdino**

### CODE REVIEW

**Comment by rjworks** [comment]
Should i test?

**Comment by developerdino** [comment]
> Should i test?

I have only written the tests to make the changes against. Nothing to test yet. Once the PR is out of Draft mode it will be ready for testing.

File: tests/NotProfaneTest.php [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+        yield ['analytics'];
+        yield ['as sure'];
+        yield ['coke'];
+        yield ['document'];
+        yield ['get it'];
+        yield ['hows it going'];
+        yield ['i have a hole in my pocket'];
+        yield ['madison bumgardner'];
+        yield ['Mick'];
+        yield ['scrape'];
```
Comment (sebastianheise) [inline tests/NotProfaneTest.php:31]:
```
yield ['passport'];
```
